//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro_de_errores_ZRP1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int index {
            get {
                return ((int)(this["index"]));
            }
            set {
                this["index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOscuro {
            get {
                return ((bool)(this["IsOscuro"]));
            }
            set {
                this["IsOscuro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Provedor {
            get {
                return ((int)(this["Provedor"]));
            }
            set {
                this["Provedor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CadenaDeConexion {
            get {
                return ((string)(this["CadenaDeConexion"]));
            }
            set {
                this["CadenaDeConexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImpresoraDefault {
            get {
                return ((string)(this["ImpresoraDefault"]));
            }
            set {
                this["ImpresoraDefault"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CT~~CD,~CC^~CT~\r\n^XA\r\n^MMT\r\n^LS0\r\n^FO15,855^GFA,3584,3584,8,,:0FC,3C7,3018,6008,4" +
            "EEC,CB0C,C904,CFCC,4FEC,6018,303,1FE,0FC,,::::7FI01FCJ01F8,:::::::::::::::::::::" +
            "7SF8,:::::T08,,:::I01F,003IF,00JFC,01KF,03KF8,07KFC,0LFC,0FF803FE,1FEI0FF,1FCI07" +
            "F,:3F8I03F8,:3FJ01F8,:3FJ01FC,:7FK0FC,7EK0FC,::::7SF8,::::::,::K01IF8,K0KF,J07KF" +
            "E,I01MF8,I03MFC,I0OF,001OF8,003OFC,007OFE,00QF,01QF8,03QFC,07QFE,:0SF,1MFC03IF,1" +
            "MF800IF8,1LFEI07FF8,3LFEI03FFC,3LFCI01FFC,:3LF8J0FFE,:3LF8J07FE,3LFK07FE,3LFK07F" +
            "F,::1KFEK07FF,:9KFCK07FF,8KFCK07FF,8KF8K0IF,87JF8K0FFE,43JFL0FFE,41IFEK01FFE,40I" +
            "FCK01FFE,603FFL01FFE,2P03FFC,3P03FFC,3P07FFC,18O0IF8,1CN01IF8,0EN01IF,0FN03FFE,0" +
            "78M0IFE,03CL01IFC,01FL03IF8,01F8K0JF,00FFJ03JF,007FE001JFE,003OF8,I0OF,I07MFE,I0" +
            "1MF8,J0LFE,02001KF801,078003IFC0078,0FEI01F8I0FC,0FFN01FC,1FEN01FE,1FCO0FF,3FCO0" +
            "7F,3F8O07F,7FP03F8,:7FP01F8,7EP01FC,FEQ0FC,::FCQ0FC,FCQ0FE,:::FEQ0FC,:7EQ0FC,7EP" +
            "01FC,7FP01FC,:3FP03F8,3F8O03F8,3FCO07F8,1FCO0FF,1FEO0FF,0FFN01FE,07F8M03FC,07FCM" +
            "07FC,03FEL01FF8,01FF8K03FF,00FFEK0FFE,007FF8I03FFC,003IF003IF8,001OF,I07MFC,I03M" +
            "F8,J0LFE,J03KF8,K07IFC,L01F8,,:O01E,N01FFE,001CJ07IFC,00FCI01JFE,03FCI03KF8,07F8" +
            "I07KFC,0FFCI0LFE,1FFC001FFC0FFE,3FFI01FF001FF,3FCI03FEI0FF8,7F8I03FCI07F8,7FJ07F" +
            "8I03FC,7EJ07FJ01FC,FEJ0FFJ01FC,FEJ0FEK0FC,:FEI01FCK0FE,:FEI03F8K0FE,FEI03F8K0FC," +
            "7FI07F8K0FC,7FI07FK01FC,7F800FFK01FC,3FC01FEK03FC,3FE07FCK07F8,1KFCK0FF8,0KF8J03" +
            "FF,0KFJ01FFE,07IFEJ07FFC,01IFCJ07FF8,00IFK03FF,001FCK03FE,P03F8,P03C,,:::R03F8,N" +
            "03KF8,J07OF8,3SF8,7SF8,::7PF,7KF8,7F8,7FF8,7IF,3IFE,07IFC,00JF8,001JF,I03IFE,J0J" +
            "FC,J01JF8,K03JF,L07IFE,M0JF8,M01JF,N03IFE,O07IFC,P0JF8,Q0IF8,Q01FF8,Q07FF8,P07IF" +
            "8,O07JF8,N03JFE,M01KF,M0KF8,L07JF8,K03JFC,J01JFE,J0KF,I07JF8,003JFC,01JFE,0KF,3J" +
            "F,7IF8,7FF8,7F8,7KF,7OFC,7SF8,::03RF8,K07NF8,O0KF8,R01F8,,:::::Q03FF8,M07LF8,I07" +
            "PF8,7SF8,:::7NFE,7IFC,7FC,7FFC,7IF8,1JF,03IFE,007IFC,001JF8,I03JF,J07IFE,K0JFC,K" +
            "01JF,L03IFE,M0JFC,M01JF8,N03JF,O03IFE,P07IF8,Q07FF8,Q01FF8,P01IF8,P0JF8,O0KF8,N0" +
            "7JFC,M03JFE,L01KF,L0KF8,K07JFC,J03JFE,I01JFE,I0KF,007JF8,03JFC,1JFE,7JF,7IF,7FF," +
            "7F8,7LF8,7PFE,7SF8,::003QF8,L07MF8,P0JF8,S018,,::L01F,K07IFC,J03KF8,J0LFE,I03MF8" +
            ",I07MFC,001OF,003IF003IF8,007FF8I03FFC,00FFEK0FFE,01FF8K03FF,03FEL01FF8,07FCM0FF" +
            "8,07F8M03FC,0FFN01FE,1FEN01FE,1FCO0FF,3FCO07F,3F8O07F8,3F8O03F8,7FP03F8,7FP01FC," +
            "7EP01FC,:FEQ0FC,::FEQ0FE,:::FEQ0FC,:7EQ0FC,7EP01FC,7FP01FC,7FP01F8,3FP03F8,3F8O0" +
            "3F8,3F8O07F,1FCO0FF,1FEO0FE,0FFN01FE,0FF8M03FC,07FCM07FC,03FEM0FF8,01FFL03FF,00F" +
            "FCK0FFE,007FFJ03FFC,003FFE001IF8,001OF,I0NFE,I03MF8,J0LFE,J03KF8,K0JFC001,03J07F" +
            "CI038,07CO0FC,0FFN01FC,1FEN01FE,1FCO0FE,3FCO07F,3F8O07F,7F8O03F8,7FP03F8,7FP01F8" +
            ",7EP01FC,:FEQ0FC,::FCQ0FC,FCQ0FE,::FEQ0FE,FEQ0FC,7EQ0FC,:7EP01FC,7FP01FC,3FP03F8" +
            ",3F8O03F8,3F8O07F8,1FCO07F,1FEO0FF,0FFN01FE,0FF8M03FE,07FCM07FC,03FEM0FF8,01FFL0" +
            "3FF,00FFCK07FF,007FFJ01FFE,003FFEI0IF8,001OF,I0NFE,I03MF8,I01MF,J07KFC,K0JFE,L07" +
            "FC,^FS\r\n^FO156,1130^GB42,164,42^FS\r\n^FT189,1294^A0B,34,33^FR^FH\\^FD MATERIAL ^FS" +
            "\r\n^FO139,792^GB496,0,4^FS\r\n^FO6,792^GB163,0,5^FS\r\n^FO473,793^GB0,516,5^FS\r\n^FO30" +
            "8,793^GB0,517,4^FS\r\n^FO142,0^GB0,1309,3^FS\r\n^FT278,573^A0B,34,33^FH\\^FD{8}^FS\r\n^" +
            "FT100,1292^A0B,34,33^FH\\^FDREPORTE DE PROBLEMA^FS\r\n^FT130,1293^A0B,23,28^FH\\^FDP" +
            "RADERAS US32^FS\r\n^BY3,3,44^FT62,229^BCB,,N,N\r\n^FD>:{3}^FS\r\n^FT49,783^A0B,31,31^F" +
            "H\\^FD{2}^FS\r\n^FO489,1236^GB42,63,42^FS\r\n^FT522,1299^A0B,34,33^FR^FH\\^FD HU ^FS\r\n" +
            "^FO321,1177^GB42,117,42^FS\r\n^FT354,1294^A0B,34,33^FR^FH\\^FD ORDEN ^FS\r\n^BY2,3,84" +
            "^FT628,1297^BCB,,N,N\r\n^FD>:{4}^FS\r\n^BY2,3,86^FT293,1296^BCB,,N,N\r\n^FD>:{6}^FS\r\n^" +
            "BY2,3,80^FT456,1293^BCB,,N,N\r\n^FD>:{7}^FS\r\n^FO324,643^GB46,138,46^FS\r\n^FT360,781" +
            "^A0B,37,36^FR^FH\\^FDTURNO : ^FS\r\n^FT357,624^A0B,34,33^FH\\^FD{9}^FS\r\n^FT129,782^A" +
            "0B,31,31^FH\\^FD{11}^FS\r\n^FT676,1309^A0B,34,33^FH\\^FDINFORMACION ADICIONAL^FS\r\n^F" +
            "T205,778^A0B,48,48^FH\\^FDDETALLES DEL PROBLEMA^FS\r\n^FO242,583^GB46,199,46^FS\r\n^F" +
            "T278,782^A0B,37,36^FR^FH\\^FDPROBLEMA : ^FS\r\n^FO406,507^GB46,269,46^FS\r\n^FT442,77" +
            "6^A0B,37,36^FR^FH\\^FDDEPARTAMENTO :^FS\r\n^FT438,493^A0B,34,33^FH\\^FD{0}^FS\r\n^FO48" +
            "8,607^GB46,168,46^FS\r\n^FT524,775^A0B,37,36^FR^FH\\^FDESTATUS : ^FS\r\n^FT950,1267^A" +
            "0B,28,28^FH\\^FB1225,9,,^FD{5}^FS\r\n^FT602,597^A0B,34,33^FH\\^FD{10}^FS\r\n^FO570,610" +
            "^GB46,169,46^FS\r\n^FT606,779^A0B,37,36^FR^FH\\^FDUSUARIO : ^FS\r\n^FT519,598^A0B,34," +
            "33^FH\\^FD{1}^FS\r\n^FT518,1230^A0B,28,28^FH\\^FD{4}^FS\r\n^FT352,1166^A0B,28,28^FH\\^F" +
            "D{7}^FS\r\n^FT185,1120^A0B,28,28^FH\\^FD{6}^FS\r\n^LRY^FO145,1^GB0,791,79^FS^LRN\r\n^LR" +
            "Y^FO641,2^GB0,1302,44^FS^LRN\r\n^PQ1,0,1,Y^XZ")]
        public string LabelModel {
            get {
                return ((string)(this["LabelModel"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LabelKind {
            get {
                return ((string)(this["LabelKind"]));
            }
            set {
                this["LabelKind"] = value;
            }
        }
    }
}
